name: Run check format lint and unittests
on:
  push:
    branches:
      - dev

jobs:
  run-linters-unittests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          ls -a;
          bash -c ./scripts/./install.sh;
      - name: run linters
        run: |
          .venv/bin/poetry run flake8 ep_bandpass_filter_selector/selector.py
          .venv/bin/poetry run ruff ep_bandpass_filter_selector/selector.py
      - name: run unittests
        run: |
          .venv/bin/poetry run pytest

  build_public_package:
    needs: run-linters-unittests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          ls -a;
          bash -c ./scripts/./install.sh;
      - name: build package
        run: .venv/bin/poetry build
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_name: "test-ep-bandpass-filter-selector"
          repository_url: "https://test.pypi.org/legacy/"
