name: Run check format lint and unittests
on:
  push:
    branches:
      - main

jobs:
  rebuild-images-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: install dependencies
        run: bash -c ./scripts/./install.sh
      - name: run test format code
        run: |
          .venv/bin/poetry run ruff check .
          # .venv/bin/poetry run ruff format .
      - name: run unittests
        run: |
          .venv/bin/poetry run pytest
