name: Run check format lint and unittests
on:
  push:
    branches:
      - py3.8

jobs:
  rebuild-images-prod:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          ls -a;
          bash -c ./scripts/./install.sh;
      - name: run test format code
        run: |
          .venv/bin/poetry run ruff check .
      - name: run unittests
        run: |
          .venv/bin/poetry run pytest